spring:
  application:
    name: skillresume
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
    url: jdbc:h2:mem:testdb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    open-in-view: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true


springdoc:
  paths-to-match:
  - /api/**/v1/**
  swagger-ui:
    use-root-path: true
#  packages-to-scan:
#  packages-to-scan:
#    - com.skillsresume.curriculum


